# Generated by Django 5.1.1 on 2025-12-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='min_duration',
            field=models.CharField(default='60', max_length=200),
        ),
    ]
