# Generated by Django 4.2.17 on 2025-12-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_couple_min_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='min_duration',
            field=models.IntegerField(default=60),
        ),
    ]
