# Generated by Django 4.2.17 on 2025-12-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_day_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
    ]
