# Generated by Django 4.2.17 on 2025-12-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_groups_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couples', to='main.group'),
        ),
    ]
