# Generated by Django 4.2.17 on 2025-12-14 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_couple_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couples', to='main.day'),
        ),
    ]
