# Generated by Django 4.2.17 on 2025-12-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_couple_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couple',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='couples',
            field=models.ManyToManyField(blank=True, related_name='days', to='main.couple'),
        ),
    ]
