# Generated by Django 5.1.1 on 2025-12-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_couple_day_day_couples'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='dance_class',
            field=models.CharField(default='B', max_length=100),
        ),
    ]
