# Generated by Django 5.1.1 on 2025-12-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_couple_dance_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couple',
            old_name='dance_class',
            new_name='dance_class_lat',
        ),
        migrations.AddField(
            model_name='couple',
            name='dance_class_stt',
            field=models.CharField(default='B', max_length=100),
        ),
    ]
