# Generated by Django 5.1.1 on 2025-12-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_dance_class_couple_dance_class_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='focus',
            field=models.CharField(default='S|L', max_length=10),
        ),
    ]
