# Generated by Django 5.1.1 on 2025-12-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_trainer_focus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='dance_class_lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='couple',
            name='dance_class_stt',
            field=models.CharField(max_length=100),
        ),
    ]
