# Generated by Django 4.2.17 on 2025-12-22 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_couple_dance_class_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='end_time',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AddField(
            model_name='day',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
