# Generated by Django 5.1.1 on 2025-12-23 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_day_end_time_day_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_interval_start', models.TimeField(default=datetime.time(0, 0))),
                ('time_interval_end', models.TimeField(default=(0, 0))),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='day', to='main.trainer'),
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='group_lesson',
        ),
        migrations.AddField(
            model_name='trainer',
            name='group_lesson',
            field=models.ManyToManyField(blank=True, related_name='trainer', to='main.grouplesson'),
        ),
    ]
