# Generated by Django 4.2.17 on 2025-12-23 18:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_grouplesson_day_trainers_remove_trainer_group_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouplesson',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_lessons', to='main.day'),
        ),
        migrations.AlterField(
            model_name='grouplesson',
            name='time_interval_end',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
