# Generated by Django 4.2.17 on 2025-12-23 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_grouplesson_day_alter_grouplesson_time_interval_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerDayAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_availabilities', to='main.day')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_availabilities', to='main.trainer')),
            ],
            options={
                'unique_together': {('day', 'trainer')},
            },
        ),
    ]
