# Generated by Django 6.0 on 2025-12-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_trainerdayavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='focus',
            field=models.CharField(default='S&L', max_length=10),
        ),
    ]
