# Generated by Django 6.0 on 2026-01-04 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_trainer_focus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='primary',
        ),
        migrations.AddField(
            model_name='group',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grouplesson',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='group_lessons', to='main.group'),
        ),
        migrations.CreateModel(
            name='DancersAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.JSONField(default=list)),
                ('dancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancer_availabilities', to='main.dancer')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dancer_availabilities', to='main.day')),
            ],
        ),
    ]
