# Generated by Django 6.0 on 2026-01-07 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerClubs', '0003_club_profile_picture'),
        ('main', '0023_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couples', to='TrainerClubs.club'),
        ),
        migrations.AddField(
            model_name='dancersavailability',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dancer_availabilities', to='TrainerClubs.club'),
        ),
        migrations.AddField(
            model_name='day',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='TrainerClubs.club'),
        ),
        migrations.AddField(
            model_name='group',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='TrainerClubs.club'),
        ),
        migrations.AddField(
            model_name='grouplesson',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_lessons', to='TrainerClubs.club'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainers', to='TrainerClubs.club'),
        ),
        migrations.AddField(
            model_name='trainerdayavailability',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_availabilities', to='TrainerClubs.club'),
        ),
    ]
