# Generated by Django 6.0 on 2026-01-09 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerClubs', '0003_club_profile_picture'),
        ('main', '0024_couple_club_dancersavailability_club_day_club_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couple',
            name='club',
        ),
        migrations.AlterField(
            model_name='day',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day', to='TrainerClubs.club'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='TrainerClubs.club'),
        ),
    ]
