# Generated by Django 6.0 on 2026-01-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerClubs', '0003_club_profile_picture'),
        ('main', '0025_remove_couple_club_alter_day_club_alter_trainer_club'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainerdayavailability',
            unique_together={('day', 'trainer', 'club')},
        ),
    ]
