# Generated by Django 6.0 on 2026-01-10 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_trainerdayavailability_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainerdayavailability',
            unique_together={('day', 'trainer')},
        ),
    ]
