# Generated by Django 6.0 on 2026-02-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_trainer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='DancerClassLat',
            field=models.CharField(choices=[('e', 'E'), ('d', 'D'), ('c', 'C'), ('b', 'B'), ('a', 'A'), ('s', 'S'), ('pro', 'PRO')], default='c', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='DancerClassSTT',
            field=models.CharField(choices=[('e', 'E'), ('d', 'D'), ('c', 'C'), ('b', 'B'), ('a', 'A'), ('s', 'S'), ('pro', 'PRO')], default='c', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trainer_focus',
            field=models.CharField(choices=[('stt', 'STT'), ('lat', 'LAT'), ('s&l', 'S&L')], default='s&l', max_length=10),
        ),
    ]
