# Generated by Django 6.0 on 2026-02-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_userprofile_dancerclasslat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
