# Generated by Django 6.0 on 2026-02-14 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_trainer_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancer',
            name='dance_class_lat',
            field=models.CharField(default='B', max_length=100),
        ),
        migrations.AddField(
            model_name='dancer',
            name='dance_class_stt',
            field=models.CharField(default='B', max_length=100),
        ),
        migrations.AddField(
            model_name='dancer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dancers', to='main.group'),
        ),
        migrations.AddField(
            model_name='dancer',
            name='min_duration',
            field=models.IntegerField(default=60),
        ),
    ]
