# Generated by Django 6.0 on 2026-02-14 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_dancer_dance_class_lat_dancer_dance_class_stt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dancer',
            name='uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dancer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dancer', to=settings.AUTH_USER_MODEL),
        ),
    ]
