# Generated by Django 6.0 on 2026-02-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_dancer_uid_dancer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
