# Generated by Django 6.0 on 2026-02-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_couple_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='dancers',
            field=models.ManyToManyField(blank=True, related_name='days', to='main.dancer'),
        ),
    ]
