# Generated by Django 4.2.17 on 2026-02-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_day_dancers'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancer',
            name='in_couple',
            field=models.BooleanField(default=False),
        ),
    ]
