# Generated by Django 4.2.17 on 2026-02-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_dancer_in_couple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancer',
            name='time_availability',
        ),
        migrations.AddField(
            model_name='couple',
            name='man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='man', to='main.dancer'),
        ),
        migrations.AddField(
            model_name='couple',
            name='woman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='woman', to='main.dancer'),
        ),
        migrations.AddField(
            model_name='dancer',
            name='sex',
            field=models.CharField(default='male', max_length=10),
        ),
    ]
