# Generated by Django 4.2.17 on 2026-02-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_dancer_time_availability_couple_man_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
