# Generated by Django 4.2.17 on 2026-02-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_userprofile_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='sex',
            new_name='user_sex',
        ),
    ]
