# Generated by Django 4.2.17 on 2026-02-20 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0039_rename_sex_userprofile_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='couple', to=settings.AUTH_USER_MODEL),
        ),
    ]
