# Generated by Django 4.2.17 on 2026-02-20 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerClubs', '0003_club_profile_picture'),
        ('main', '0040_alter_couple_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couples', to='TrainerClubs.club'),
        ),
        migrations.AddField(
            model_name='dancer',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dancers', to='TrainerClubs.club'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couples', to='main.group'),
        ),
        migrations.AlterField(
            model_name='dancer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dancers', to='main.group'),
        ),
    ]
