# Generated by Django 6.0 on 2026-01-09 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerClubs', '0003_club_profile_picture'),
        ('schedule', '0002_fill_user_nulls'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedschedulefile',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UploadedScheduleFile', to='TrainerClubs.club'),
        ),
    ]
