# Generated by Django 6.0 on 2026-01-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('value', models.TextField(blank=True)),
                ('bg_color', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'unique_together': {('row', 'col')},
            },
        ),
    ]
