# Generated by Django 6.0 on 2026-01-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='bg_color',
            new_name='color',
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cell',
            name='col',
            field=models.CharField(max_length=50),
        ),
    ]
