# Generated by Django 6.0 on 2026-01-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_rename_bg_color_cell_color_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cell',
            new_name='SheetCell',
        ),
    ]
