# Generated by Django 6.0 on 2026-01-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerClubs', '0003_club_profile_picture'),
        ('sheet', '0003_rename_cell_sheetcell'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetcell',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SheetCells', to='TrainerClubs.club'),
        ),
    ]
