# Generated by Django 6.0 on 2026-01-13 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_trainerdayavailability_unique_together'),
        ('sheet', '0004_sheetcell_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetcell',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SheetCells', to='main.group'),
        ),
    ]
