# Generated by Django 6.0 on 2026-01-16 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerClubs', '0003_club_profile_picture'),
        ('main', '0027_alter_trainerdayavailability_unique_together'),
        ('sheet', '0005_sheetcell_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetcell',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SheetCells', to='TrainerClubs.club'),
        ),
        migrations.AlterField(
            model_name='sheetcell',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SheetCells', to='main.group'),
        ),
        migrations.AlterUniqueTogether(
            name='sheetcell',
            unique_together={('club', 'group', 'row', 'col')},
        ),
    ]
