# Generated by Django 6.0 on 2026-01-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerClubs', '0002_alter_club_club_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='club_profiles/'),
        ),
    ]
